# Generated by Django 6.0 on 2026-01-31 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='owner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requester_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='expected_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_for', to='books.book'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('exchanged', 'Exchanged'), ('unavailable', 'Unavailable')], db_index=True, default='available', max_length=20),
        ),
    ]
