# Generated by Django 6.0 on 2026-02-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_message_exchangerequest_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
