# Generated by Django 6.0 on 2026-02-09 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='books.book'),
        ),
    ]
