# Generated by Django 6.0 on 2026-02-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_exchangerequest_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
