# Generated by Django 6.0 on 2026-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
